export const sources = {
  ej10: ['Eloquent JavaScript, fourth edition, chapter 10: Modules', 'https://eloquentjavascript.net/10_modules.html'],
  ej11: ['Eloquent JavaScript, fourth edition, chapter 11: Asynchronous Programming', 'https://eloquentjavascript.net/11_async.html'],
  ej18: ['Eloquent JavaScript, fourth edition, chapter 18: HTTP and Forms', 'https://eloquentjavascript.net/18_http.html'],
  ej20: ['Eloquent JavaScript, fourth edition, chapter 20: Node.js', 'https://eloquentjavascript.net/20_node.html'],
  ej08: ['Eloquent JavaScript, fourth edition, chapter 8: Bugs and Errors', 'https://eloquentjavascript.net/08_error.html'],
  db: ['Fundamentals of Database Systems, seventh edition (publisher)', 'https://www.pearson.com/en-us/subject-catalog/p/fundamentals-of-database-systems/P200000003546'],
  http: ['Node.js 24: HTTP', 'https://nodejs.org/download/release/latest-v24.x/docs/api/http.html'],
  fs: ['Node.js 24: File system', 'https://nodejs.org/download/release/latest-v24.x/docs/api/fs.html'],
  sqlite: ['Node.js 24: SQLite', 'https://nodejs.org/download/release/latest-v24.x/docs/api/sqlite.html'],
  test: ['Node.js 24: Test runner', 'https://nodejs.org/download/release/latest-v24.x/docs/api/test.html'],
  crypto: ['Node.js 24: Crypto', 'https://nodejs.org/download/release/latest-v24.x/docs/api/crypto.html'],
  https: ['Node.js 24: HTTPS and TLS', 'https://nodejs.org/download/release/latest-v24.x/docs/api/https.html'],
  fk: ['SQLite: Foreign Key Support', 'https://www.sqlite.org/foreignkeys.html'],
  create: ['SQLite: CREATE TABLE', 'https://www.sqlite.org/lang_createtable.html'],
  select: ['SQLite: SELECT', 'https://www.sqlite.org/lang_select.html'],
  tx: ['SQLite: Transactions', 'https://www.sqlite.org/lang_transaction.html'],
  planner: ['SQLite: Query Planning', 'https://www.sqlite.org/queryplanner.html'],
  backup: ['SQLite: Online Backup API', 'https://www.sqlite.org/backup.html'],
  docker: ['Docker: Get started', 'https://docs.docker.com/get-started/'],
  volumes: ['Docker: Persisting container data', 'https://docs.docker.com/get-started/docker-concepts/running-containers/persisting-container-data/'],
  session: ['OWASP: Session Management', 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html'],
  password: ['OWASP: Password Storage', 'https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html'],
  csrf: ['OWASP: Cross-Site Request Forgery Prevention', 'https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html'],
  upload: ['OWASP: File Upload', 'https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html'],
  authz: ['OWASP: Authorization', 'https://cheatsheetseries.owasp.org/cheatsheets/Authorization_Cheat_Sheet.html'],
  tls: ['OWASP: Transport Layer Security', 'https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Security_Cheat_Sheet.html'],
  oauth: ['RFC 9700: Best Current Practice for OAuth 2.0 Security', 'https://www.rfc-editor.org/rfc/rfc9700.html'],
  github: ['GitHub: Authorizing OAuth apps', 'https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps'],
  emails: ['GitHub: REST API endpoints for emails', 'https://docs.github.com/en/rest/users/emails'],
  google: ['Google: OpenID Connect', 'https://developers.google.com/identity/openid-connect/openid-connect'],
  jose: ['jose: JWT verification and remote JWKS', 'https://github.com/panva/jose'],
  busboy: ['Busboy: API, parser limits and file events', 'https://github.com/mscdex/busboy'],
  sharp: ['Sharp: Constructor and input limits', 'https://sharp.pixelplumbing.com/api-constructor/'],
  sharpmeta: ['Sharp: Input metadata', 'https://sharp.pixelplumbing.com/api-input/'],
  openssl: ['OpenSSL 3.5: openssl-req', 'https://docs.openssl.org/3.5/man1/openssl-req/'],
  sqlcipher: ['SQLCipher: Keying, rekey, export and integrity APIs', 'https://www.zetetic.net/sqlcipher/sqlcipher-api/'],
  ciphernode: ['JourneyApps: SQLCipher Node bindings and supported platforms', 'https://github.com/journeyapps/node-sqlcipher'],
  original: ['01-edu: forum source subject', 'https://github.com/01-edu/public/tree/master/subjects/forum']
};
export const checkedDate = '2026-10-05';
